# Broadcasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

In [1]:
# Import Numpy
import numpy as np

In [3]:
# Adding constant vector to each row of a larger matrix
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

# Empty matrix in the shape of x
y = np.empty_like(x)

In [4]:
# Add vector 'v' to each row of the matrix 'x' using looping
for i in range(4):
    y[i, :] = x[i, :] + v
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

If the matrix `x` is large using a loop is expensive, Note that adding the vector `v` to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [5]:
# Stacking 4 copies of 'v' on top of each other
vv = np.tile(v, (4, 1))
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [7]:
y_ = x + vv
y_

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

Broadcasting allows us to do this operation without making multiple copies of a matrix saving the space complexity.
Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

General Rule - 

(M, N) +-*/ (1, N) --> (M, N)

(M, N) +-*/ (M, 1) --> (M, N)

(M, 1) +-*/ R (real nummber) --> (M, 1)

(1, N) +-*/ R --> (1, N)

In [10]:
y = x + v
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

## Applications of Broadcasting
Finding shortest distance in a 3D plane from a point.

Computing Outer product

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5])

# Reshape and outer product
print(np.reshape(a, (3, 1))*b)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [12]:
# Add vector to each row
print(a + x)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]
